name: Check Dead Links

on: [push, pull_request]

jobs:
  dead-links:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Check dead links with lychee
      uses: lycheeverse/lychee-action@v1.1.1
      with:
        args: README.md
